# Generated by Django 2.0 on 2018-03-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduletest', '0002_load_负荷文件名称'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='上网电价',
            field=models.CharField(default='None', max_length=200000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='load',
            name='内部售电价',
            field=models.CharField(default='None', max_length=200000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='load',
            name='市政电价',
            field=models.CharField(default='None', max_length=200000),
            preserve_default=False,
        ),
    ]
