# Generated by Django 2.0 on 2018-03-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduletest', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='load',
            name='username',
            field=models.CharField(default='hkx', max_length=200),
            preserve_default=False,
        ),
    ]
