# Generated by Django 2.0 on 2018-04-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduletest', '0008_lhsx_projectinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lhsx_projectinfo',
            name='并网模式',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='lhsx_projectinfo',
            name='燃气内燃机最大台数',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lhsx_projectinfo',
            name='燃气内燃机最大规模',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lhsx_projectinfo',
            name='燃气内燃机最小规模',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lhsx_projectinfo',
            name='燃气轮机最大台数',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lhsx_projectinfo',
            name='燃气轮机最大规模',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lhsx_projectinfo',
            name='燃气轮机最小规模',
            field=models.FloatField(default=0),
        ),
    ]
