# Generated by Django 2.0 on 2018-04-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduletest', '0009_auto_20180411_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='lhsx_projectinfo',
            name='达产率',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='lhsx_projectinfo',
            name='并网模式',
            field=models.CharField(default='全额上网', max_length=200),
        ),
    ]
