# Generated by Django 2.0 on 2018-04-12 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduletest', '0010_auto_20180412_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lhsx_projectinfo',
            name='达产率',
        ),
    ]
