# Generated by Django 2.0 on 2018-04-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduletest', '0011_remove_lhsx_projectinfo_达产率'),
    ]

    operations = [
        migrations.AddField(
            model_name='lhsx_projectinfo',
            name='达产率',
            field=models.CharField(default='1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,', max_length=1000),
        ),
    ]
