# Generated by Django 2.0 on 2019-01-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_author_blog_entry_projectrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrecord',
            name='working_days',
            field=models.FloatField(),
        ),
    ]
